import {Shell} from '@/components/Shell'
import CommandMap from '@/components/CommandMap'
import {Copilot} from '@/components/Copilot'
const actors=[['EMBER FALCON','State-aligned intrusion cluster','HIGH','Government • Telecom'],['SABLE TIDE','Espionage-oriented cluster','MEDIUM','Energy • Research'],['IRON VEIL','Destructive/disruptive cluster','HIGH','Critical Infrastructure']]
export default function Page(){return <Shell><main className="page">
<section className="ee-hero"><div><span className="ee-kicker">Geopolitical cyber situational awareness</span><h1>Track campaigns without overstating attribution.</h1><p>Follow public reporting on nation-state and state-aligned activity while keeping source quality, attribution confidence, targeting, and observed techniques explicit.</p></div><div className="ee-hero-side"><div className="ee-stat"><span>Campaign mode</span><strong>Monitored</strong></div><div className="ee-stat"><span>Attribution</span><strong>Confidence scored</strong></div><div className="ee-stat"><span>Actor names</span><strong>Demo</strong></div><div className="ee-stat"><span>Source model</span><strong>Public</strong></div></div></section>
<section className="ee-section"><div className="ee-section-head"><div><span className="ee-kicker">Campaign picture</span><h2>Global cyber warfare view</h2></div><span className="demo-flag">DEMO ACTOR NAMES</span></div><CommandMap/></section>
<section className="ee-section"><div className="ee-grid three">{actors.map(a=><section className="panel actor-card" key={a[0]}><div className="panel-title">THREAT ACTOR PROFILE</div><h2>{a[0]}</h2><p>{a[1]}</p><div className="watch-row"><span>Confidence</span><b>{a[2]}</b></div><div className="watch-row"><span>Targeting</span><b>{a[3]}</b></div><div className="tag-row"><span>T1078</span><span>T1059</span><span>T1021</span><span>T1486</span></div></section>)}</div></section>
<section className="ee-section"><div className="ee-callout"><strong>Attribution standard.</strong> Campaign attribution remains confidence-scored and source-linked. Fictional demo actor names are never presented as claims about real governments or organizations.</div></section>
</main><Copilot/></Shell>}
