import {Shell} from '@/components/Shell'
import {IntelFeed} from '@/components/IntelFeed'
import SituationBrief from '@/components/SituationBrief'
import {Copilot} from '@/components/Copilot'
const categories=[['Ransomware','Campaigns, disclosures, known exploitation'],['Vulnerabilities','CISA KEV + NVD CVE intelligence'],['Malware & IOCs','Infrastructure, hashes, URLs, command-and-control'],['Phishing','Credential theft and malicious infrastructure'],['Botnets / DDoS','Coordinated malicious infrastructure and disruption'],['Critical Infrastructure','Operational technology and essential-service context'],['Dark Web','Publicly observable criminal-ecosystem reporting'],['Outages','Operational context around service disruption']]
export default function Page(){return <Shell><main className="page">
<section className="ee-hero"><div><span className="ee-kicker">Intelligence fusion center</span><h1>One picture from thousands of signals.</h1><p>EagleEye normalizes authoritative advisories, vulnerability intelligence, ransomware disclosures, indicators, and analyst context into a prioritized operating picture.</p></div><div className="ee-hero-side"><div className="ee-stat"><span>Official feeds</span><strong>Active</strong></div><div className="ee-stat"><span>OSINT layer</span><strong>Active</strong></div><div className="ee-stat"><span>Customer telemetry</span><strong>Ready</strong></div><div className="ee-stat"><span>Source labeling</span><strong>Required</strong></div></div></section>
<section className="ee-section"><div className="ee-section-head"><div><span className="ee-kicker">Collection</span><h2>Intelligence domains</h2></div><span className="live-badge">● FEEDS ACTIVE</span></div><div className="category-grid">{categories.map(x=><div className="category-card" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section>
<section className="ee-section"><div className="ee-grid two"><IntelFeed/><SituationBrief/></div></section>
<section className="ee-section"><div className="ee-callout"><strong>Evidence before animation.</strong> Official sources, OSINT claims, customer detections, and demo telemetry remain visibly distinct. EagleEye should never imply that an animated map event is verified simply because it looks live.</div></section>
</main><Copilot/></Shell>}
